# Generated by Django 5.2.3 on 2025-06-30 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='idea',
        ),
        migrations.AddField(
            model_name='pitch',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pitch',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pitch',
            name='funding',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='goal',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='stage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
