# Generated by Django 4.2.7 on 2025-09-29 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('unique_value_proposition', models.TextField()),
                ('target_market', models.TextField()),
                ('business_model', models.TextField()),
                ('competitive_analysis', models.TextField()),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equity_offered', models.DecimalField(decimal_places=2, max_digits=5)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('ecommerce', 'E-Commerce'), ('other', 'Other')], max_length=20)),
                ('founding_date', models.DateField()),
                ('team_size', models.IntegerField()),
                ('website', models.URLField(blank=True)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('partially_funded', 'Partially Funded'), ('fully_funded', 'Fully Funded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(limit_choices_to={'user_type': 'founder'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_acquired', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(limit_choices_to={'user_type': 'investor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
            options={
                'unique_together': {('investor', 'startup')},
            },
        ),
    ]
